<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Filters applied</name>
   <tag></tag>
   <elementGuidId>fb2b1ff4-a7ed-48d7-96ec-30614d293955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.x-flyout__button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e39b96e3-53c8-463f-9e13-ce20009dbff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-marko</name>
      <type>Main</type>
      <value>{&quot;onclick&quot;:&quot;toggle s0-28_1-9-0-1[0]-0-0-6-5-4[0]-flyout false&quot;}</value>
      <webElementGuid>1e6280a9-b913-4004-ae33-68bc1cba7ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66070da8-16d2-4c38-968b-7e8a05677439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>s0-28_1-9-0-1[0]-0-0-6-5-4[0]-flyout</value>
      <webElementGuid>9bbed238-bce8-41f2-8c4e-2529576fd6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-flyout__button</value>
      <webElementGuid>9a4561b3-106b-47fe-8e18-04234fe4072e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ace00dc-5dec-4862-8e7f-f4396d3e0bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>459a5549-4b42-4189-bcda-8eed380a36b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3 filters applied</value>
      <webElementGuid>e0cd1bad-7f55-4539-9388-2d4c8dfe3518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s0-28_1-9-0-1[0]-0-0-6-5-4[0]-flyout&quot;)/button[@class=&quot;x-flyout__button&quot;]</value>
      <webElementGuid>c5795483-609a-4fd8-9638-de70b8948c5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>c212483a-d075-4bdb-bbb2-3370e1eac75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s0-28_1-9-0-1[0]-0-0-6-5-4[0]-flyout']/button</value>
      <webElementGuid>df9fb14c-63b0-4769-aaaf-8a92d9521b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='filter applied'])[1]/preceding::button[1]</value>
      <webElementGuid>6e3a1664-1924-4e98-a9b4-56fd667a5ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li/div/button</value>
      <webElementGuid>ec01f237-4285-4305-b6bd-8ae95643408b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '3 filters applied' or . = '3 filters applied')]</value>
      <webElementGuid>6beaa29d-39d7-4e49-b57e-bc7f315545e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
