<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cell Phones  and Smartphones</name>
   <tag></tag>
   <elementGuidId>2a292fc2-0f5b-41ac-9ecf-261274be0f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='s0-17-12_2-0-1[0]-0-0']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1fbf6e1f-37ff-4666-be70-ee8d93b554a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>{&quot;eventFamily&quot;:&quot;LST&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;actionKind&quot;:&quot;NAVSRC&quot;,&quot;operationId&quot;:&quot;2489527&quot;,&quot;flushImmediately&quot;:false,&quot;eventProperty&quot;:{&quot;parentrq&quot;:&quot;871d02461810adb9e0453b74fff5c922&quot;,&quot;pageci&quot;:&quot;8188dfcf-a835-40c8-86da-356528d12bc2&quot;,&quot;moduledtl&quot;:&quot;mi:4337|iid:1|li:9750|luid:26|c:26|uxComponentGroup:CATEGORY_NAV_STRUCTURED_VERTICAL_GROUP|level:2&quot;}}</value>
      <webElementGuid>c2eb8eb8-13ee-4259-9b39-169a73c3bd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_sp</name>
      <type>Main</type>
      <value>p2489527.m4337.l9750.c26</value>
      <webElementGuid>8b3374f2-505b-4d91-9170-d6e5a6fd36de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-textlink b-textlink--parent</value>
      <webElementGuid>c0f7ae3f-a83d-4920-8ef0-722fe2072f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ebay.com/b/Cell-Phones-Smartphones/9355/bn_320094</value>
      <webElementGuid>a7c872cf-3461-4835-b0c4-c853cb37449d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cell Phones &amp; Smartphones</value>
      <webElementGuid>47b9ea37-52f3-4305-bb42-4c081a4b296e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s0-17-12_2-0-1[0]-0-0&quot;)/ul[1]/li[3]/a[@class=&quot;b-textlink b-textlink--parent&quot;]</value>
      <webElementGuid>03f5cdbd-f76f-4dea-9a1e-749414a4a3dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='s0-17-12_2-0-1[0]-0-0']/ul/li[3]/a</value>
      <webElementGuid>f5751245-8fea-40ce-8655-cb567d75cbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cell Phones &amp; Smartphones')]</value>
      <webElementGuid>8f2487ac-3dc5-4d5a-9054-917d7a05c297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transmitters'])[1]/following::a[1]</value>
      <webElementGuid>c4fb0f7c-b9de-4b65-9489-0fabde2b7a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Styluses'])[1]/following::a[2]</value>
      <webElementGuid>23ca2944-07db-43ac-9789-5d6c5bb17bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display Phones'])[1]/preceding::a[1]</value>
      <webElementGuid>79df60ea-bb98-40be-99ad-1fe27fcac30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixed Lots'])[1]/preceding::a[2]</value>
      <webElementGuid>4f7b7d65-e71b-4d70-bed9-c8d275636d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cell Phones &amp; Smartphones']/parent::*</value>
      <webElementGuid>2af1d809-f8a6-443c-a84a-cc4338ea1fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ebay.com/b/Cell-Phones-Smartphones/9355/bn_320094')]</value>
      <webElementGuid>2ac62161-aefc-4520-91e0-9a5ad6c7ccdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li[3]/a</value>
      <webElementGuid>c115e27e-04b1-4a5d-8811-f7f1c80903b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ebay.com/b/Cell-Phones-Smartphones/9355/bn_320094' and (text() = 'Cell Phones &amp; Smartphones' or . = 'Cell Phones &amp; Smartphones')]</value>
      <webElementGuid>6f39d9a2-9f7a-491e-8847-3762a1d4a232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
