<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Item Location Tab</name>
   <tag></tag>
   <elementGuidId>42ae8c4c-b80b-4b9d-b3ca-285497aa310d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s0-28_1-9-0-1[0]-0-0-6-5-4[0]-flyout']/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d68967f-113d-45bc-9dba-66923d1893ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ebay.com/b/4-0-4-4-Inch-Cell-Phones-Smartphones/9355/bn_591691?_udlo=100000&amp;_udhi=1000000&amp;rt=nc&amp;LH_PrefLoc=98&amp;mag=1</value>
      <webElementGuid>4e4d44d7-d857-4f9d-89c0-22f6eac931e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>{&quot;eventFamily&quot;:&quot;LST&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;actionKind&quot;:&quot;NAVSRC&quot;,&quot;operationId&quot;:&quot;2489527&quot;,&quot;flushImmediately&quot;:false,&quot;eventProperty&quot;:{&quot;moduledtl&quot;:&quot;mi%3A4118%7Ciid%3A1%7Cselected%3A1%7Cglobal%3A1%7CaspectURLParam%3ALH_PrefLoc%7Cli%3A8173%7Cluid%3A113%7C&quot;,&quot;pageci&quot;:&quot;9e7a2039-3c76-4e62-a9ff-32c712b36532&quot;,&quot;parentrq&quot;:&quot;872d596c1810a7b8944652d0fff3ab04&quot;}}</value>
      <webElementGuid>cf2b145c-fcdc-4a28-9489-912cc53e86bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_sp</name>
      <type>Main</type>
      <value>p2489527.m4118.c1</value>
      <webElementGuid>d91e3bff-e399-46e1-bf07-6f78a402cfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Item Location: US Only filter applied</value>
      <webElementGuid>ba10cc17-82c3-4fe0-a838-fc86d075b61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s0-28_1-9-0-1[0]-0-0-6-5-4[0]-flyout&quot;)/div[@class=&quot;x-flyout__content flyout-notice flyout-notice--information flyout-notice--top-right&quot;]/ul[@class=&quot;brm__aspect-list&quot;]/li[@class=&quot;brm__aspect-item brm__aspect-item--applied&quot;]/a[1]</value>
      <webElementGuid>94fd9dfa-c46b-4867-b563-0b9fc3ff28fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s0-28_1-9-0-1[0]-0-0-6-5-4[0]-flyout']/div/ul/li[3]/a</value>
      <webElementGuid>eeed74af-b0c3-4f5f-82d7-26f126a3e447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='filter applied'])[2]/following::a[1]</value>
      <webElementGuid>4f7320a6-23bd-45e9-ab69-e5a1aeee1f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ebay.com/b/4-0-4-4-Inch-Cell-Phones-Smartphones/9355/bn_591691?_udlo=100000&amp;_udhi=1000000&amp;rt=nc&amp;LH_PrefLoc=98&amp;mag=1')]</value>
      <webElementGuid>be7810e4-7b15-42a8-aef4-e72aceb93056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li/div/div/ul/li[3]/a</value>
      <webElementGuid>823fc4db-63dc-43a3-ab34-f6590e6f50fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ebay.com/b/4-0-4-4-Inch-Cell-Phones-Smartphones/9355/bn_591691?_udlo=100000&amp;_udhi=1000000&amp;rt=nc&amp;LH_PrefLoc=98&amp;mag=1' and (text() = 'Item Location: US Only filter applied' or . = 'Item Location: US Only filter applied')]</value>
      <webElementGuid>1d1b282c-7a77-4575-b883-1a384ba30163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
